### ISSUE TITLE
Could use more specific documentation

### ISSUE THREAD

**Issue by roycornelissen** [sylvaingirardbe/strapi-provider-upload-azure#3]
The README points to this page: https://strapi.io/documentation/3.0.0-alpha.x/guides/upload.html#usage, which is a really generic description of the upload plugin. As a newbie Strapi user, I find it hard to figure out how to enable this provider. Could use more specific documentation on where and how to configure it. I guess I need a Azure blob storage connection string, container name, etc. But where do I set that?

**Comment by sylvaingirardbe** [comment]
You need to install the provider as documented in the link you described as having a really generic description. Once you have done that, you can select the provider in the configuration of your Upload plugin in the strapi admin pages. You'll come to find that the stuff you need to fill in is pretty self-explanatory...

**Comment by roycornelissen** [comment]
@sylvaingirardbe ah thanks, pardon my ignorance 🤷‍♂️ I couldn't find those settings easily but after I did it was indeed straightforward to configure. Thanks for the plugin!

A general question though... it's storing the access key in the database now, any way to let Strapi take it from an environment variable?

**Comment by sylvaingirardbe** [comment]
At the moment that's not the case. There seems to be a suggestion [here](https://github.com/strapi/strapi/issues/4090#issuecomment-534955265) on how to fix this. I'd be more than willing to take a PR if you're up to it.
